// Writes src/version.ts from package.json's version, so pluginVersion is available inside the
// TS program without importing '../package.json' -- that import sits above `rootDir: "src"` in
// tsconfig.json (TS6059 on emit), and even where tsc tolerates it, it survives verbatim into
// bundled output with no guaranteed JSON interop for every consumer of the emitted bundle.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const { version } = JSON.parse(readFileSync(`${root}/package.json`, 'utf8'));
writeFileSync(
  `${root}/src/version.ts`,
  `// Auto-generated by scripts/gen-version.mjs from package.json -- do not edit.\nexport const version = ${JSON.stringify(version)};\n`,
);
